# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v2
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install Ubuntu Packages
        run: |
          sudo apt install -y libcurl4-openssl-dev      
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "curl", "rcmdcheck", "BiocManager"))
          BiocManager::install(version = "3.14")
          bio_pkgs <- c(
            "AnnotationDbi", "circlize",  "clusterProfiler", "ComplexHeatmap", "corrplot", 
            "data.table", "devtools", "dplyr", "EnvStats", "eulerr", "factoextra", 
            "FactoMineR", "forcats", "forestplot", "ggfortify", "ggplot2", "ggpubr", 
            "graphics", "grDevices", "grid", "limma", "missMDA", "org.Hs.eg.db", "purrr", 
            "RColorBrewer", "ReactomePA", "readr",  "readxl", "reshape2", "scales", 
            "stats", "stringr", "survival", "survivalAnalysis", "tibble", "tidyr", 
            "tidyselect")
          BiocManager::install(bio_pkgs)
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
